name: Step 6 — DAST (OWASP ZAP)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  dast-zap:
    name: OWASP ZAP — Baseline Scan
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start SecureShop via Docker Compose
        run: |
          docker compose up -d --build
          echo "Attente démarrage (30s)..."
          sleep 30

      - name: Vérifier que les services sont up
        run: |
          curl -f http://localhost/api/users/health     || echo "user-service KO"
          curl -f http://localhost/api/products/health  || echo "product-service KO"
          curl -f http://localhost/api/orders/health    || echo "order-service KO"

      - name: ZAP Baseline Scan — API Gateway
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost'
          rules_file_name: '.github/zap-rules.tsv'
          fail_action: false
          allow_issue_writing: false
          

      - name: ZAP Baseline Scan — user-service
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost/api/users/health'
          fail_action: false
          allow_issue_writing: false
          artifact_name: zap-users-report
        continue-on-error: true

      - name: ZAP Baseline Scan — product-service
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost/api/products/health'
          fail_action: false
          allow_issue_writing: false
          artifact_name: zap-products-report
        continue-on-error: true

      - name: ZAP Baseline Scan — order-service
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost/api/orders/health'
          fail_action: false
          allow_issue_writing: false
          artifact_name: zap-orders-report
        continue-on-error: true

      - name: Stop Docker Compose
        if: always()
        run: docker compose down