name: Full DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:

  sast:
    name: "Step 2 — SAST"
    uses: ./.github/workflows/sast.yml

  sca:
    name: "Step 3 — SCA"
    needs: sast
    uses: ./.github/workflows/sca.yml

  secrets:
    name: "Step 4 — Secrets Detection"
    needs: sca
    uses: ./.github/workflows/secrets.yml

  iac:
    name: "Step 7 — IaC Scanning"
    needs: secrets
    uses: ./.github/workflows/iac.yml

  dast:
    name: "Step 6 — DAST"
    needs: iac
    uses: ./.github/workflows/dast.yml